### ISSUE TITLE
[Task] 경제사전 검색창 컴포넌트

### ISSUE THREAD

**Issue by tmdqls2257** [oxopolitics-internship-for-codestates/MoneyPig#12]
### ISSUE
  * Detail:  헤더 컴포넌트 만들기

### SCREENSHOT
![image](https://user-images.githubusercontent.com/54207332/195277424-46642aac-da1d-469e-a513-35fb76507989.png)

### TODO
- [x]  검색창
- [x]  x 버튼 클릭후 인풋 벨류 삭제
- [x]  키워드 유효성 검사
- [x]  자동완성 기능 (max 5개 이하는 그만큼 줄어들기)
- [x]  더미 데이터(quiz)=> economyData.json 파일로 변경
- [x]  Input 컴포넌트 리팩토링(재사용 가능하게) 

### 1h
