### ISSUE TITLE
[tast] quizService 만들기

### ISSUE THREAD

**Issue by tmdqls2257** [oxopolitics-internship-for-codestates/MoneyPig#32]
### ISSUE
  * Detail:  firebase와 연동할 수 있는 service를 구현

### TODO
- [x]  firebase에서 모든 데이터를 받아오는 함수 구현
- [x]  firebase에 데이터를 넣어주는 함수 구현
- [x]  단일 데이터 받아오기

### CODE

```tsx
import {
  collection,
  query,
  QueryDocumentSnapshot,
  SnapshotOptions,
  addDoc,
  updateDoc,
  doc,
  getDoc,
  getDocs,
} from 'firebase/firestore';

import fireStore from '../src/firebase/Firebase';
import { Quiz } from '../src/store/QuizStore';

export const quizConverter = {
  toFireStore: (quiz: Quiz) => {
    return {
      id: quiz.id,
      title: quiz.title,
      userId: quiz.userId,
      createdAt: quiz.createdAt,
      answer: quiz.answer,
      time: quiz.time,
      keyword: quiz.keyword,
      type: quiz.type,
      description: quiz.description,
      options: quiz.options,
    };
  },

  fromFirestore: (
    snapshot: QueryDocumentSnapshot,
    options: SnapshotOptions,
  ) => {
    const data = snapshot.data(options);
    console.log(data);

    return new Quiz(
      data.id,
      data.title,
      data.userId,
      data.createdAt,
      data.answer,
      data.time,
      data.keyword,
      data.type,
      data.description,
      data.options,
    );
  },
};

class QuizService {
  constructor() {}

  async quizUpload(data: Quiz): Promise<void> {
    await addDoc(collection(fireStore, 'quizes'), data).then(async res => {
      const frankDocRef = doc(fireStore, 'quizes', res.id);
      await updateDoc(frankDocRef, {
        id: res.id,
      });
    });
  }

  async getQuizes() {
    const quizes: Quiz[] = [];
    const q = query(collection(fireStore, 'quizes'));
    await getDocs(q).then(res => {
      res.forEach(doc => {
        quizes.push(JSON.parse(JSON.stringify(doc.data())));
      });
    });
    return quizes;
  }

  async getQuiz(id: string) {
    try {
      const docRef = doc(fireStore, 'quizes', id);
      const docSnap = await getDoc(docRef);
      const quiz: Quiz = JSON.parse(JSON.stringify(docSnap.data()));
      return quiz;
    } catch (err) {
      console.log(err);
    }
  }
}

const quizService = new QuizService();

export default quizService;

```
